services:
  database:
    image: mysql:9.0
    volumes:
      - ps37569:/var/lib/mysql
    ports:
      - '2511:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nam
      MYSQL_USER: nam
      MYSQL_PASSWORD: Ex@mple12345

volumes:
  ps37569:

